### ISSUE TITLE
System.NotSupportedException encountered on Aspect.Weave in WCF service

### ISSUE THREAD

**Issue by Try2BWise** [Virtuoze/NConcern#11]
I'm not sure if this is an NConcern or CNeptune issue. Since I encounter it when implementing the code from the NConcern ReadMe, I'm opting to post it here.

Based on the readme.md I've created a WCF project with the Tracer and Logging classes exactly as written. I've modified the Calculator service to include implicit joinpoints as shown below:
```
using NConcern;
using System.ServiceModel;

namespace NConcern_WCF
{
    [ServiceContract]
    public class Calculator
    {
        [OperationContract]
        public int Add(int a, int b)
        {
            int answer = 0;
            Aspect.Weave<Logging>(typeof(OperationContractAttribute));
            answer = a + b;
            Aspect.Release<Logging>(typeof(OperationContractAttribute));
            return answer;
        }
    }
}
```
I'm hosting the service in Local IIS and testing it using SoapUI. If I disable the joinpoints the service runs correctly. However, when I enable the joinpoints I recieve the following exception on the Aspect.Weave call.
```
System.NotSupportedException occurred
  HResult=0x80131515
  Message=type 'System.Web.ApplicationServices.AuthenticationService, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not managed by CNeptune and cannot be supervised.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```
Output from SoapUI is
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <s:Fault>
         <faultcode xmlns:a="http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher">a:InternalServiceFault</faultcode>
         <faultstring xml:lang="en-US">type 'System.Web.ApplicationServices.AuthenticationService, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not managed by CNeptune and cannot be supervised.</faultstring>
         <detail>
            <ExceptionDetail xmlns="http://schemas.datacontract.org/2004/07/System.ServiceModel" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
               <HelpLink i:nil="true"/>
               <InnerException i:nil="true"/>
               <Message>type 'System.Web.ApplicationServices.AuthenticationService, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not managed by CNeptune and cannot be supervised.</Message>
               <StackTrace><![CDATA[at NConcern.Aspect.Directory.Entry.Pointer(MethodBase method)
   at NConcern.Aspect.Directory.Entry..ctor(Type type, MethodBase method, Activity activity)
   at NConcern.Aspect.Directory.Obtain(MethodBase method)
   at NConcern.Aspect.Directory.Add[T](MethodBase method)
   at NConcern.Aspect.Weave[T](Func`2 pattern)
   at NConcern_WCF.Calculator.<Neptune>.<Authentic>.Add(Calculator this, Int32 a, Int32 b) in C:\git\NConcern WCF\NConcern WCF\Calculator.svc.cs:line 13
   at NConcern_WCF.Calculator.Add(Int32 a, Int32 b)
   at SyncInvokeAdd(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)]]></StackTrace>
               <Type>System.NotSupportedException</Type>
            </ExceptionDetail>
         </detail>
      </s:Fault>
   </s:Body>
</s:Envelope>
```
I'm far from as experienced as I want to be in diagnosing and fixing situations like this. I appreciate the help. Thanks!

**Comment by Virtuoze** [comment]
hi, thank you for sharing, can you try to define manual joinpoint like this and tell me if it change something for you?

    Aspect.Weave<Logging>(method => method is MethodInfo && method.DeclaringType == typeof(Calculator));

**Comment by Try2BWise** [comment]
I implemented the first suggestion you made:
```
Aspect.Weave<Logging>(method => method is MethodInfo && method.DeclaringType == typeof(Calculator));
```
and with CNeptune still referenced in the project I get the following error when building:
```
The command ""C:\git\NConcern WCF\packages\CNeptune.1.1.0\build\CNeptune.exe" "C:\git\NConcern WCF\NConcern WCF\NConcern WCF.csproj" "Debug"" exited with code -532462766.
```

If I remove CNeptune from the project it builds successfully. However, I receive a very similar exception:
```
System.NotSupportedException: 'type 'NConcern_WCF.Calculator, NConcern WCF, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not managed by CNeptune and cannot be supervised.'
```
I can eliminate exceptions by using code from the example in the solution file from the project:
```
var _operationContractJoinpoint = new Func<MethodBase, bool>(_Method => _Method.IsDefined(typeof(Calculator), true));
Aspect.Weave<Logging>(_operationContractJoinpoint);
...
Aspect.Release<Logging>(_operationContractJoinpoint);
```
Unfortunately, weaving never occurs. No breakpoints in the Tracer or Logging classes are reached and no logging output is seen. Adding or removing CNeptune as a project reference doesn't change behavior.

**Comment by Virtuoze** [comment]
Hi, you got the good scenario when CNeptune failed to rewrite IL when building. Indeed, there is a bug in CNeptune that I fixed but not release. Please refer to this post for more details : 
[https://github.com/Virtuoze/CNeptune/issues/9#](https://github.com/Virtuoze/CNeptune/issues/9#)

**Comment by Virtuoze** [comment]
CNeptune has been patched : the bug is now fixed in version 1.2.0
[https://www.nuget.org/packages/CNeptune](https://www.nuget.org/packages/CNeptune)

Unfortunately during test, I found a performance issue on startup because NConcern try to locate pointcut in all framework that take long time... I have to patch NConcern to ignore Framework Assemblies.

**Comment by elcergey** [comment]
Experiencing the same error. Is not yet fixed ?

**Comment by Virtuoze** [comment]
Do you use NConcern 4.1.0 & CNeptune 1.2.1 ? (latest versions)

**Comment by elcergey** [comment]
I use NConcern 4.1.0. Do I also need to install/reference CNeptune ?

**Comment by Virtuoze** [comment]
CNeptune must be installed on assembly you want to inject. NConcern is an API to control how to inject. In some can Injector and injected are not the same project, but sometimes it is the case.

**Comment by elcergey** [comment]
With CNeptune, it works.  Thanks.

**Comment by songle321** [comment]
System.NotSupportedException:
NConcern:4.1.0&&CNeptune:1.2.1; Aspect.Weave<TranCtrl>(TranCtrl.Condition);
gitUrl:https://github.com/songle321/WCFTest.git
