### ISSUE TITLE
Generic<T>

### ISSUE THREAD

**Issue by Mickey-Knox** [Virtuoze/NConcern#17]
Hi,

I have an issue when I use generic types and inheritance. I get an System.BadImageFormatException when I instantiate a generic class which inherits from another generic class.

I did some tests to identify which cases work and which don't :

1. Class<T> -> OK
2. Class<T> : Base -> OK
3. Class : Base<int> -> OK
4. Class<T> : Base<int> -> OK

5.  Class<T> : Base<T> -> KO

ILSpy shows the following error when I try visualize the none working class (case 5) :
System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.Disassembler.DisassemblerHelpers.WriteTo(TypeReference type, ITextOutput writer, ILNameSyntax syntax)
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.WriteParameters(Collection`1 parameters)
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleMethodInternal(MethodDefinition method)
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleType(TypeDefinition type)
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleType(TypeDefinition type)
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleType(TypeDefinition type)
   at ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler.DisassembleType(TypeDefinition type)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass17.<DecompileAsync>b__16()

Thank you!

**Comment by jho1965us** [comment]
May be related to https://github.com/Virtuoze/CNeptune/issues/10
